hw10/hw10/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw10/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import RegisterView
from .forms import LoginForm

from . import views

app_name = "users"

urlpatterns = [
    path(
        "login",
        LoginView.as_view(
            template_name="users/login.html",
            authentication_form=LoginForm,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("logout", LogoutView.as_view(), name="logout"),
    path("signup", RegisterView.as_view(), name="signup"),
    path('profile/', views.profile, name='profile'),
]

hw10/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default_avatar.png', upload_to='profile_images')

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

hw10/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile


class RegisterForm(UserCreationForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter username"}
        ),
    )

    password1 = forms.CharField(
        label="Password",
        required=True,
        min_length=5,
        max_length=25,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "new-password", "class": "form-control"}
        ),
    )

    password2 = forms.CharField(
        label="Password confirmation",
        required=True,
        min_length=5,
        max_length=25,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "new-password", "class": "form-control"}
        ),
    )

    class Meta:
        model = User
        fields = [
            "username",
            "password1",
            "password2",
        ]


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter username"}
        ),
    )
    password = forms.CharField(
        max_length=25,
        min_length=5,
        required=True,
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )

    class Meta:
        model = User
        fields = [
            "username",
            "password",
        ]

class DeleteForm(forms.ModelForm):
    username = forms.CharField(
        max_length=100, required=True, widget=forms.HiddenInput()
    )

    class Meta:
        model = User
        fields = [
            "username",
        ]

...

class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ['avatar']

hw10/users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View

from .forms import RegisterForm, LoginForm, DeleteForm, ProfileForm


class RegisterView(View):
    form_class = RegisterForm
    template_name = "users/signup.html"

    def get(self, request):
        if request.user.is_authenticated:
            return redirect(to="quotes:main")
        return render(request, self.template_name, context={"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Your account '{username}' was created...")
            return redirect(to="users:login")
        else:
            messages.error(request, "Not registered...")
            return render(request, self.template_name, context={"form": form})


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to="quotes:main")

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.changed_data["username"]
            messages.success(request, f"Your account '{username}' was created...")
            return redirect(to="users:login")
        else:
            messages.error(request, "Not registered...")
            return render(request, "users/signup.html", context={"form": form})

    return render(request, "users/signup.html", context={"form": RegisterForm()})




def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to="quotes:main")

    if request.method == "POST":
        user = authenticate(
            username=request.POST["username"], password=request.POST["password"]
        )
        if user is None:
            messages.error(request, "Username or password didn't match")
            return redirect(to="users:login")

        login(request, user)
        return redirect(to="quotes:main")

    return render(request, "users/login.html", context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:main')

@login_required
def profile(request):
    return render(request, 'users/profile.html')

@login_required
def deleteuser(request):
    if not request.user.is_authenticated:
        return redirect(to="quotes:main")

    if request.method == "POST":
        form = DeleteForm(request.POST)
        if form.data.get("username") == request.user.username:
            if request.user.delete():
                messages.success(request, 'User was deleted successfully')
                return redirect(to="quotes:main")
            else:
                messages.error(request, 'User was not deleted')
        else:
            messages.error(request, f'User was not deleted. Data of form is wrong {form.data["username"]=}, {request.user.username=}')

    return render(request, "users/delete.html", context={"form": DeleteForm(), "username":request.user })

...

@login_required
def profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users:profile')

    profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'users/profile.html', {'profile_form': profile_form})

hw10/users/templates/users/login.html
{% extends 'quotes/base.html' %}

{% block content %}
<style>
    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }

    label {
        width: 100%;
    }
</style>
<div class="form-signin rounded-3 bg-light">
    {% if messages %}
    <div>
        {% for message in messages %}
        <div role="alert" class="text-center alert alert-primary {% if message.tags %} alert-{{ message.tags }} {% endif %}">{{ message }}</div>
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div role="alert" class="text-center alert alert-warning">{{ error }}</div>
        {% endfor %}
    </div>
    {% endif %}
    {% for error in form.non_field_errors %}
    <div>
        <div role="alert" class="text-center alert alert-warning">{{ error }}</div>
    </div>
    {% endfor %}
    <h1 class="h3 mb-3 fw-normal text-center">Please login</h1>
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <div class="mb-3 mt-3">
            <label for="username" class="form-label">Username:
                {{ form.username }}
            </label>
            <span>{{ form.errors.username }}</span>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password:
                {{ form.password }}
            </label>
            <span>{{ form.errors.password }}</span>
        </div>

        <div class="mb-3 text-center">
            <button class="btn btn-primary" type="submit">Login</button>
            <button class="btn btn-secondary" type="reset ">Reset</button>
        </div>
    </form>
</div>


{% endblock %}

hw10/users/templates/users/profile.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h1>Profile page: {{user.username}}</h1>
    <img src="{{ user.profile.avatar.url }}" alt="avatar of user"/>
</div>

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col-md-5">
            <div class="form-group">
                <label class="small mb-1">Change Avatar:</label>
                {{ profile_form.avatar }}
                <span>{{ profile_form.errors.avatar }}</span>
            </div>
        </div>
    </div>
    <div class="grid">
        <button type="submit">Save Changes</button>
        <button type="reset" class="secondary">Reset</button>
    </div>

</form>

{% endblock content %}

hw10/users/templates/users/signup.html
{% extends 'quotes/base.html' %}

{% block content %}
<style>
    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }

    label {
        width: 100%;
    }
</style>
<div class="form-signin rounded-3 bg-light">
    {% if messages %}
    <div>
        {% for message in messages %}
        <div role="alert" class="text-center alert alert-primary {% if message.tags %} alert-{{ message.tags }} {% endif %}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    {% for error in form.non_field_errors %}
    <div>
        <div role="alert" class="text-center alert alert-warning">{{ error }}</div>
    </div>
    {% endfor %}
    <h1 class="h3 mb-3 fw-normal text-center">Please SignUp</h1>
    <form method="post" action="{% url 'users:signup' %}">
        {% csrf_token %}
        <div class="mb-3 mt-3">
            <label for="username" class="form-label">Username:
                {{ form.username }}
            </label>
            <span>{{ form.errors.username }}</span>
        </div>
        <div class="mb-3">
            <label for="id_password1" class="form-label">Password:
                {{ form.password1 }}
            </label>
            <span>{{ form.errors.password1 }}</span>
        </div>
        <div class="mb-3">
            <label for="id_password2" class="form-label"> Password confirmation:
                {{ form.password2 }}
            </label>
            <span>{{ form.errors.password2 }}</span>
        </div>

        <div class="mb-3 text-center">
            <button class="btn btn-primary" type="submit">SignUp</button>
            <button class="btn btn-secondary" type="reset ">Reset</button>
        </div>
    </form>
</div>


{% endblock %}