hw10/hw10/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw10/quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='main'),
    path('<int:page>', views.main, name='main_paginate'),
    path('author/<str:author>', views.author, name='author'),
    path('tag/<str:tag>', views.tag, name='tag'),
    path('tag/<str:tag>/<int:page>', views.tag, name='tag_paginate'),
    path('add/author', views.AddAuthorView.as_view(), name='add_author'),
    path('add/tag', views.AddTagView.as_view(), name='add_tag'),
    path('add/quote', views.add_quote, name='add_quote'),
]

hw10/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=120, unique=True)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=120)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.fullname}"


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self) -> str:
        return f"{self.name}"


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

hw10/quotes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import Author, Quote, Tag

# fullname = models.CharField(max_length=120)
# born_date = models.CharField(max_length=50)
# born_location = models.CharField(max_length=120)
# description = models.TextField()
# created_at = models.DateTimeField(auto_now_add=True)


class AuthorForm(forms.ModelForm):
    fullname = forms.CharField(
        max_length=120,
        required=True,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter fullname"}
        ),
    )
    born_date = forms.CharField(
        max_length=50,
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    born_location = forms.CharField(
        max_length=120,
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    description = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={"class": "form-control"}),
    )

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class TagForm(forms.ModelForm):
    name = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter name"}
        ),
    )

    class Meta:
        model = Tag
        fields = ["name"]

    # quote =  models.TextField()
    # tags = models.ManyToManyField(Tag)
    # author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)


class QuoteForm(forms.ModelForm):
    quote = forms.CharField(
        required=True,
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "Enter quote"}
        ),
    )
    author = forms.IntegerField(widget=forms.Select())
    # tags = forms.MultiValueField(widget=forms.SelectMultiple(fields=))

    class Meta:
        model = Quote
        fields = ["quote"]
        exclude = ["tags", "author"]

hw10/quotes/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views import View
from django.contrib import messages
from django.contrib.auth.models import User

from .models import Quote, Author, Tag

from .forms import AuthorForm, QuoteForm, TagForm


PER_PAGE = 4

# def main_mongodb_version(request, page=1):
#     from .utils import get_mongodb
#     db = get_mongodb()
#     quotes = db.quotes.find({}).limit(15)
#     paginator = Paginator(list(quotes), per_page=PER_PAGE)

#     context = {"quotes": paginator.page(page)}
#     return render(request, "quotes/index.html", context)


def main(request, page=1):
    quotes = Quote.objects.all()
    paginator = Paginator(quotes, per_page=PER_PAGE)

    context = {"quotes": paginator.page(page)}
    return render(request, "quotes/index.html", context)


def author(request, author: str):
    try:
        author = Author.objects.get(fullname=author)
    except:
        author = None
    context = {"author": author}
    return render(request, "quotes/author.html", context)


def tag(request, tag: str, page: int = 1):
    quotes = []
    tag_id = None
    try:
        tag_id = Tag.objects.get(name=tag).id
    except:
        ...
    print(f"{tag=},{tag_id=}")
    if tag_id:
        quotes = Quote.objects.filter(tags=tag_id)

    paginator = Paginator(quotes, per_page=PER_PAGE)
    context = {"quotes": paginator.page(page), "tag_query": tag}
    return render(request, "quotes/tag.html", context)

    tag = Tag.objects.get(name=tag)
    paginator = Paginator(tag, per_page=PER_PAGE)

    context = {"tag": paginator.page(page)}
    return render(request, "quotes/tag.html", context)


@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            fullname = form.cleaned_data["fullname"]
            messages.success(request, f"Author '{fullname}' was created...")
            return render(
                request, "quotes/add_author.html", context={"form": AuthorForm()}
            )
        else:
            messages.error(request, "Not added...")
            return render(request, "quotes/add_author.html", context={"form": form})

    context = {"form": AuthorForm()}
    return render(request, "quotes/add_author.html", context)


@login_required
def add_quote(request, id: int = 0):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == "POST":
        form = QuoteForm(request.POST)
        print(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.quote = form.cleaned_data['quote']
            new_quote.author = Author.objects.filter(pk=form.cleaned_data['author']).get()
            new_quote.save()

            choice_tags = Tag.objects.filter(
                name__in=request.POST.getlist("tags")
            )
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            messages.success(request, "Quote was added....")
        else:
            messages.error(request, "Not added....")
            return render(request, "quotes/add_quote.html", {"tags": tags, "authors": authors, "form": form})

    return render(request, "quotes/add_quote.html", {"tags": tags, "authors": authors, "form": QuoteForm()})


class AddAuthorView(LoginRequiredMixin, View):
    form_class = AuthorForm
    template_name = "quotes/add_author.html"

    def get(self, request):
        return render(request, self.template_name, context={"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            fullname = form.cleaned_data["fullname"]
            messages.success(request, f"Author '{fullname}' was created...")
            return render(
                request, self.template_name, context={"form": self.form_class}
            )
        else:
            messages.error(request, "Not added...")
            return render(request, self.template_name, context={"form": form})


class AddTagView(LoginRequiredMixin, View):
    form_class = TagForm
    template_name = "quotes/add_tag.html"

    def get(self, request):
        return render(request, self.template_name, context={"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            fullname = form.cleaned_data["name"]
            messages.success(request, f"Tag '{fullname}' was created...")
            return render(
                request, self.template_name, context={"form": self.form_class}
            )
        else:
            messages.error(request, "Not added...")
            return render(request, self.template_name, context={"form": form})

hw10/quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}
{% block content %}
{% if messages %}
<div>
    {% for message in messages %}
    <div role="alert"
        class="text-center alert alert-primary {% if message.tags %} alert-{{ message.tags }} {% endif %}">{{ message }}
    </div>
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div role="alert" class="text-center alert alert-warning">{{ error }}</div>
    {% endfor %}
</div>
{% endif %}
{% for error in form.non_field_errors %}
<div>
    <div role="alert" class="text-center alert alert-warning">{{ error }}</div>
</div>
{% endfor %}
<div class="author-details">
    <h3 class="author-title">Add author</h3>
    <form action="" method="post">
        {% csrf_token %}
        <div class="mb-3 mt-3">
            <label for="id_fullname" class="form-label w-100">Full name:
                {{ form.fullname }}
            </label>
            <span>{{ form.errors.fullname }}</span>
        </div>
        <div class="mb-3 mt-3">
            <label for="id_born_date" class="form-label w-100">Born Date:
                {{ form.born_date }}
            </label>
            <span>{{ form.errors.born_date }}</span>
        </div>
        <div class="mb-3 mt-3">
            <label for="id_born_location" class="form-label w-100">Born Location:
                {{ form.born_location }}
            </label>
            <span>{{ form.errors.born_location }}</span>
        </div>
        <div class="mb-3 mt-3">
            <label for="id_description" class="form-label w-100">Description:
                {{ form.description }}
            </label>
            <span>{{ form.errors.description }}</span>
        </div>
        <div class="mb-3 text-center">
            <button class="btn btn-primary" type="submit">Save</button>
            <button class="btn btn-secondary" type="reset ">Reset</button>
        </div>
    </form>
</div>

{% endblock %}

hw10/quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}
{% block content %}
{% if messages %}
<div>
    {% for message in messages %}
    <div role="alert"
        class="text-center alert alert-primary {% if message.tags %} alert-{{ message.tags }} {% endif %}">{{ message }}
    </div>
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div role="alert" class="text-center alert alert-warning">{{ error }}</div>
    {% endfor %}
</div>
{% endif %}
{% for error in form.non_field_errors %}
<div>
    <div role="alert" class="text-center alert alert-warning">{{ error }}</div>
</div>
{% endfor %}

<div class="author-details">
    <h3 class="author-title">Add quote</h3>
    <form action="" method="post">
        {% csrf_token %}
        <div class="mb-3 mt-3">
            <label for="id_fullname" class="form-label w-100">Enter the quote:
                {{ form.quote }}
            </label>
            <span>{{ form.errors.quote }}</span>
        </div>
        <div class="mb-3 mt-3">
            <label for="id_author" class="form-label w-100">Select the author:
                <select name="author">
                    <option value="" >Select Author</option>
                    {% for author in authors %}
                        <option value="{{author.id}}" {% if author.id == form.author %} selected {% endif %}
                        >{{author.fullname}}</option>
                    {% endfor %}
                </select>
            </label>
            <span>{{ form.errors.authors }}</span>
        </div>
        <div class="mb-3 mt-3">
            <label> Select tags:
                <select name="tags" multiple="multiple" required>
                    {% for tag in tags %}
                        <option value="{{tag.name}}" {% if tag in quotes_tags %} selected {% endif %}
                        >{{tag.name}}</option>
                    {% endfor %}
                </select>
            </label>
            <span>{{ form.errors.tags }}</span>
        </div>
        
        <div class="mb-3 text-center">
            <button class="btn btn-primary" type="submit">Save</button>
            <button class="btn btn-secondary" type="reset ">Reset</button>
        </div>
    </form>
</div>

{% endblock %}

hw10/quotes/templates/quotes/add_tag.html
{% extends 'quotes/base.html' %}
{% block content %}
{% if messages %}
<div>
    {% for message in messages %}
    <div role="alert"
        class="text-center alert alert-primary {% if message.tags %} alert-{{ message.tags }} {% endif %}">{{ message }}
    </div>
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div role="alert" class="text-center alert alert-warning">{{ error }}</div>
    {% endfor %}
</div>
{% endif %}
{% for error in form.non_field_errors %}
<div>
    <div role="alert" class="text-center alert alert-warning">{{ error }}</div>
</div>
{% endfor %}

<div class="author-details">
    <h3 class="author-title">Add tag</h3>
    <form action="" method="post">
        {% csrf_token %}
        <div class="mb-3 mt-3">
            <label for="id_fullname" class="form-label w-100">Enter the tag name:
                {{ form.name }}
            </label>
            <span>{{ form.errors.name }}</span>
        </div>
        <div class="mb-3 text-center">
            <button class="btn btn-primary" type="submit">Save</button>
            <button class="btn btn-secondary" type="reset ">Reset</button>
        </div>
    </form>
</div>

{% endblock %}

hw10/quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}
{% block content %}

<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span
            class="author-born-location">{{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>
</div>

{% endblock %}

hw10/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/styles.css' %}">
    <title>Quotes + Django</title>
</head>

<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if not user.is_authenticated %}
                    <a href="/users/signup" class="btn btn-primary">SignUp</a>
                    <a href="/users/login"  class="btn btn-primary">Login</a>
                    {% else %}
                    <a href="/users/logout" class="btn btn-primary" title='Username: "{{ user }}"'>Logout</a>
                    <a href="/add/add_author" class="btn btn-primary">Add author</a>
                    <a href="/quotes/tag" class="btn btn-primary">Add tag</a>
                    <a href="/add/quote" class="btn btn-primary">Add quote</a>
                    {% endif %}
                </p>
            </div>
        </div>

        {% block content%} 
        {% endblock %}

    </div>
</body>

</html>

hw10/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md">
        {% for quote in quotes %}
         <div class="quote">
            <span class="text" itemprop="text">{{ quote.quote }}</span>
            <span>by <small class="author" itemprop="author">{{ quote.author }}</small>
                <a href="{% url 'quotes:author' quote.author %}">(about)</a>
            </span>
            <div class="tags"> 
                Tags: 
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:tag' tag %}">{{tag}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a title="Now is page {{ quotes.number }} of {{ quotes.paginator.num_pages }}"
                    class="{% if not quotes.has_previous %} disabled {% endif %}"    
                    href="{% if quotes.has_previous %}  
                    {% url 'quotes:main_paginate' quotes.previous_page_number %}  {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
                </li>
                <li class="next">
                    <a title="Now is page {{ quotes.number }} of {{ quotes.paginator.num_pages }}"
                    class="{% if not quotes.has_next %} disabled {% endif %}"    
                    href="{% if quotes.has_next %}  
                    {% url 'quotes:main_paginate' quotes.next_page_number %}  {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

hw10/quotes/templates/quotes/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
    <h1>Quotes Django</h1>
</main>
</body>
</html>

hw10/quotes/templates/quotes/tag.html
{% extends 'quotes/base.html' %}
{% load extract_tags %}
{% block content %}

<div class="row">
    <div class="col-md">
        {% for quote in quotes %}
         <div class="quote">
            <span class="text" itemprop="text">{{ quote.quote }}</span>
            <span>by <small class="author" itemprop="author">{{ quote.author }}</small>
                <a href="{% url 'quotes:author' quote.author %}">(about)</a>
            </span>
            <div class="tags"> 
                Tags: 
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:tag' tag %}">{{tag}}</a>
                {% endfor %}

            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a title="Now is page {{ quotes.number }} of {{ quotes.paginator.num_pages }}"
                    class="{% if not quotes.has_previous %} disabled {% endif %}"    
                    href="{% if quotes.has_previous %}  
                    {% url 'quotes:tag_paginate' tag_query quotes.previous_page_number %}  {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
                </li>
                <li class="next">
                    <a title="Now is page {{ quotes.number }} of {{ quotes.paginator.num_pages }}"
                    class="{% if not quotes.has_next %} disabled {% endif %}"    
                    href="{% if quotes.has_next %}  
                    {% url 'quotes:tag_paginate' tag_query quotes.next_page_number %}  {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

hw10/quotes/templates/quotes/tag_edit.html
{% extends "noteapp/base_nav.html" %}
{% block nav %}
    <nav style="margin-bottom: 20px; border-bottom: 2px solid;">
        <ul>
            <li><a href="/tags" role="button">Go back to the tags page </a></li>
        </ul>
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
{% endblock %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div> 
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}